name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
    
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest
   
    steps:
      - name: Check Out Repo Docker
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./NistagramBackend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  Dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo Dotnet
        uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          
      - name: Install dependencies
        run: dotnet restore NistagramBackend/NistagramBackend.csproj #-nowarn:msb3202,nu1503 -p:RestoreUseSkipNonexistentTargets=false

      - name: Build
        run: dotnet build NistagramBackend.sln
        
      - name: Test
        run: dotnet test NistagramBackend/NistagramBackend.csproj --configuration release
          
  SonarCloud:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo SonarCloud
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  Test:
    runs-on: windows-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
     
      - name: Restore dependencies
        run: nuget restore NistagramBackend/NistagramBackend.sln
        
      - name: Build
        run: dotnet build NistagramBackend/NistagramBackend.sln --configuration Release --no-restore -o package
        
      - name: Build the Solution
        run: msbuild.exe NistagramBackend.sln
